from . ins_write 		import INS_Write
from . ins_add 			import INS_Add
from . ins_and 			import INS_And
from . ins_break 		import INS_Break
from . ins_call 		import INS_Call
from . ins_concat 		import INS_Concat
from . ins_create_frame import INS_CreateFrame
from . ins_defvar 		import INS_Defvar
from . ins_dprint 		import INS_Dprint
from . ins_eq 			import INS_Eq
from . ins_exit 		import INS_Exit
from . ins_getchar 		import INS_Getchar
from . ins_gt 			import INS_Gt
from . ins_idiv 		import INS_Idiv
from . ins_int2char 	import INS_Int2char
from . ins_jump 		import INS_Jump
from . ins_jumpifeq 	import INS_Jumpifeq
from . ins_jumpifneq 	import INS_Jumpifneq
from . ins_label 		import INS_Label
from . ins_lt 			import INS_Lt
from . ins_move 		import INS_Move
from . ins_mul 			import INS_Mul
from . ins_not 			import INS_Not
from . ins_or 			import INS_Or
from . ins_pop_frame 	import INS_PopFrame
from . ins_pops			import INS_Pops
from . ins_push_frame	import INS_PushFrame
from . ins_pushs 		import INS_Pushs
from . ins_read 		import INS_Read
from . ins_return 		import INS_Return
from . ins_setchar 		import INS_Setchar
from . ins_stri2int 	import INS_Stri2int
from . ins_strlen 		import INS_Strlen
from . ins_sub 			import INS_Sub
from . ins_type 		import INS_Type
from . ins_write 		import INS_Write
